package Projet_INM5001;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bwali
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JprêtHypothécaire = new javax.swing.JLabel();
        jdonnéesperso = new javax.swing.JLabel();
        jRevenusbruts = new javax.swing.JLabel();
        jTRevenusbruts = new javax.swing.JTextField();
        jParan = new javax.swing.JLabel();
        jMisedefonds = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTEngagements = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTMisedefonds = new javax.swing.JTextField();
        jCoui = new javax.swing.JCheckBox();
        jCnom = new javax.swing.JCheckBox();
        jTMois1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ButCalculer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTTaxesmunicipales = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTMois2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTMois3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ButEffacer = new javax.swing.JButton();
        ButSortir = new javax.swing.JButton();
        Messages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prêt Hypothécaires");

        jPanel1.setBackground(new java.awt.Color(241, 240, 240));

        JprêtHypothécaire.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JprêtHypothécaire.setForeground(java.awt.Color.darkGray);
        JprêtHypothécaire.setText("Prêt Hypothécaires");

        jdonnéesperso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jdonnéesperso.setForeground(java.awt.Color.gray);
        jdonnéesperso.setText("Entrer vos données personnelles");

        jRevenusbruts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRevenusbruts.setForeground(java.awt.Color.gray);
        jRevenusbruts.setText("* Revenus bruts ($) :");

        jTRevenusbruts.setForeground(java.awt.Color.darkGray);
        jTRevenusbruts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRevenusbrutsActionPerformed(evt);
            }
        });

        jParan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jParan.setForeground(java.awt.Color.gray);
        jParan.setText("par an");

        jMisedefonds.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMisedefonds.setForeground(java.awt.Color.gray);
        jMisedefonds.setText("* Mise de fonds ($) :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.gray);
        jLabel1.setText("* Engagements financiers ($) :");

        jTEngagements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEngagementsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.gray);
        jLabel2.setText("par mois");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.gray);
        jLabel3.setText("* Limiter vos versements mensuels ($):");

        jTMisedefonds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMisedefondsActionPerformed(evt);
            }
        });

        jCoui.setBackground(new java.awt.Color(241, 240, 240));
        jCoui.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCoui.setForeground(java.awt.Color.gray);
        jCoui.setText("Oui");
        jCoui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCouiActionPerformed(evt);
            }
        });

        jCnom.setBackground(new java.awt.Color(241, 240, 240));
        jCnom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCnom.setForeground(java.awt.Color.gray);
        jCnom.setText("Non");

        jTMois1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMois1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("par mois");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.gray);
        jLabel5.setText("Ajouter les frais fixes de la future maison (approximatifs)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.gray);
        jLabel6.setText("* Type de prêt et terme : ");

        jComboBox1.setEditable(true);
        jComboBox1.setForeground(java.awt.Color.gray);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taux fixe 10 ans", "Taux fixe 7 ans", "Taux fixe 4 ans", "Taux fixe 2 ans", "Taux fixe 1 ans" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.gray);
        jLabel7.setText("* Amortissement:");

        jComboBox2.setEditable(true);
        jComboBox2.setForeground(java.awt.Color.gray);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 ans ", "10 ans ", "15 ans", "20 ans", "25 ans", "  " }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.gray);
        jLabel8.setText("* Taux d'intérêt (%) : ");

        jTextField3.setForeground(java.awt.Color.gray);
        jTextField3.setText("3,89");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 173, 82));
        jLabel9.setText("Taux en vigueur");

        ButCalculer.setBackground(new java.awt.Color(11, 109, 11));
        ButCalculer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButCalculer.setForeground(new java.awt.Color(255, 255, 255));
        ButCalculer.setText("Calculer");
        ButCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCalculerActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.gray);
        jLabel10.setText("* Taxes municipales et ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.gray);
        jLabel11.setText("scolaires ($) :");

        jTTaxesmunicipales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTaxesmunicipalesActionPerformed(evt);
            }
        });

        jLabel12.setForeground(java.awt.Color.gray);
        jLabel12.setText("par an");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(java.awt.Color.gray);
        jLabel13.setText("* Coût d'énergie ($) :");

        jTMois2.setText(" ");
        jTMois2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMois2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.gray);
        jLabel14.setText("par mois");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.gray);
        jLabel15.setText("* Frais de corpropriété ($) :");

        jTMois3.setText(" ");
        jTMois3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMois3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.gray);
        jLabel16.setText("par mois");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.gray);
        jLabel17.setText("Résultat ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 173, 82));
        jLabel18.setText("Valeur maximale de la maison :");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        ButEffacer.setBackground(new java.awt.Color(11, 109, 11));
        ButEffacer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButEffacer.setForeground(new java.awt.Color(255, 255, 255));
        ButEffacer.setText("Effacer");
        ButEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButEffacerActionPerformed(evt);
            }
        });

        ButSortir.setBackground(new java.awt.Color(11, 109, 11));
        ButSortir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButSortir.setForeground(new java.awt.Color(255, 255, 255));
        ButSortir.setText("Sortir");
        ButSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSortirActionPerformed(evt);
            }
        });

        Messages.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdonnéesperso)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTMois2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16))))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(ButEffacer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButCalculer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ButSortir)))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTMois3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addComponent(jLabel18)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTTaxesmunicipales, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRevenusbruts)
                            .addComponent(jTMisedefonds, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMisedefonds)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTRevenusbruts, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jParan)))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTEngagements, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCnom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCoui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTMois1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))))
                    .addComponent(Messages, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JprêtHypothécaire, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(JprêtHypothécaire)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Messages, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdonnéesperso)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRevenusbruts)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRevenusbruts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jParan)
                    .addComponent(jTEngagements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMisedefonds)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTMisedefonds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCnom))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTMois2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jTMois3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTTaxesmunicipales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel17)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButCalculer)
                            .addComponent(ButEffacer)
                            .addComponent(ButSortir))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCoui)
                            .addComponent(jTMois1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     //Methodes pour 'ActionPerformed'
    //////////////////////////////////
    
    private void jTRevenusbrutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRevenusbrutsActionPerformed
        Double revenusBruts = tryChnEnDouble(jTRevenusbruts.getText(), "Entrer "
                + "un montant dans le champ « Revenus Bruts ».");
        
        jTEngagementsActionPerformed(evt);
    }//GEN-LAST:event_jTRevenusbrutsActionPerformed

    private void jTMisedefondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMisedefondsActionPerformed
         double miseDeFonds = tryChnEnDouble(jTMisedefonds.getText(), "Entrer un"
                 + " montant dans le champ « Mise de fonds ».");
        
        jTMois1ActionPerformed(evt);
    }//GEN-LAST:event_jTMisedefondsActionPerformed

    private void jCouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCouiActionPerformed

    private void jTTaxesmunicipalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTaxesmunicipalesActionPerformed
        double taxMunicipalesScol = tryChnEnDouble(jTMisedefonds.getText(),
                "Entrer un montant dans le champ « Taxes municipales et scolaires ».");    
        
        jTMois2ActionPerformed(evt);
    }//GEN-LAST:event_jTTaxesmunicipalesActionPerformed

    private void jTMois1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMois1ActionPerformed
        if(jCoui.isSelected()){   
              double limitVersement =tryChnEnDouble(jTMois1.getText(), "Entrer "
                      + "un montant dans le champ «Limiter vos versements mensuels. " );
        }
            jTTaxesmunicipalesActionPerformed(evt);
    }//GEN-LAST:event_jTMois1ActionPerformed

    private void ButCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCalculerActionPerformed
        jTRevenusbrutsActionPerformed(evt);
        Messages.setText("ButCalculerActionPerformed");
        System.out.println("");//test
               
    }//GEN-LAST:event_ButCalculerActionPerformed

    private void ButSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSortirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ButSortirActionPerformed

    private void ButEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEffacerActionPerformed
        jTRevenusbruts.setText("");
        jTEngagements.setText("");
        jTMisedefonds.setText("");
        jTMois1.setText("");
        jTMois2.setText("");
        jTMois3.setText("");
        jTTaxesmunicipales.setText("");
        jTRevenusbruts.setText("");
        Messages.setText("");
    }//GEN-LAST:event_ButEffacerActionPerformed

    private void jTEngagementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEngagementsActionPerformed
        double engagements = tryChnEnDouble(jTEngagements.getText(), "Entrer un"
                + " montant dans le champ « Engagements financiers ».");
        
        jTMisedefondsActionPerformed(evt);
    }//GEN-LAST:event_jTEngagementsActionPerformed

    private void jTMois2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMois2ActionPerformed
        double coutEnergie = tryChnEnDouble(jTMois2.getText(), "Entrer un "
                + "montant dans le champ « Coûts d'énergie ».");    
        
        jTMois3ActionPerformed(evt);
    }//GEN-LAST:event_jTMois2ActionPerformed

    private void jTMois3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMois3ActionPerformed
         double fraisProprietaire = tryChnEnDouble(jTMois3.getText(), "Entrer "
                 + "un montant dans le champ « Frais de copropriété ».");  
        
        calcAffichValMaison();
    }//GEN-LAST:event_jTMois3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
       
    }//GEN-LAST:event_jTextField7ActionPerformed

    //Methodes
    //////////
    private double tryChnEnDouble(String chaine, String msgErr){
        double dbl = 0.0;
        try {
            dbl = Double.parseDouble(chaine);        
        } catch (NumberFormatException e) {
         Messages.setText(msgErr);
        }
        return dbl;
    }
    
    private int tryChnEnInt(String chaine, String msgErr){
        int entier = 0;
        try {
            entier = Integer.parseInt(chaine);        
        } catch (NumberFormatException e) {
         Messages.setText(msgErr);
        }
        return entier;
    }
    
    private void calcAffichValMaison() {
        
        int amort;
        String amortChn = jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
        //Met nombre d'années en chiffres seulement
        amortChn = amortChn.replace("ans", "").trim();
        //Convertit en nombre de mois
        amort = 12 * tryChnEnInt(amortChn, "Vous devez choisir un "
                + "amortissement");
        
        //Pour calculer la valeur de la maison et montant du prêt
        valeurMaison = ( PretHypothecaires.calculePretHypothecaires(miseDeFonds,
                limitVersement, amort, revenusBruts, engagements, coutEnergie,
                 fraisProprietaire) );
        
        
        //Affichage du résultata (valeur de la maison)
        jTextField7.setText(valeurMaison + "");
        
        if (valeurMaison > 0) {
            montantPret = valeurMaison - miseDeFonds;
            // ... Mettre affichage 'montatn' du pret
        }
        if (valeurMaison <= 0) {
            Messages.setText("Vous n'êtes pas admissibles pour un prêt");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCalculer;
    private javax.swing.JButton ButEffacer;
    private javax.swing.JButton ButSortir;
    private javax.swing.JLabel JprêtHypothécaire;
    private javax.swing.JLabel Messages;
    private javax.swing.JCheckBox jCnom;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JCheckBox jCoui;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMisedefonds;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jParan;
    private javax.swing.JLabel jRevenusbruts;
    private javax.swing.JTextField jTEngagements;
    private javax.swing.JTextField jTMisedefonds;
    private javax.swing.JTextField jTMois1;
    private javax.swing.JTextField jTMois2;
    private javax.swing.JTextField jTMois3;
    private javax.swing.JTextField jTRevenusbruts;
    private javax.swing.JTextField jTTaxesmunicipales;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel jdonnéesperso;
    // End of variables declaration//GEN-END:variables


     //Attributs
    ////////////
    
    //Données perso
    double revenusBruts, miseDeFonds, engagements, limitVersement;
    //Infos de la maison
    double taxMunicipalesScol, coutEnergie, fraisProprietaire, valeurMaison;
    //Infos du prêt
    int amort;
    double montantPret;
    
}
